### ISSUE TITLE
Error when sharing to facebook

### ISSUE THREAD

**Issue by myounus96** [quotesnewtab/quotesnewtab#13]
I got this when I am trying to share to facebook.
![image](https://user-images.githubusercontent.com/13608139/90330328-64bed200-dfc5-11ea-9dbf-930cd09d12a9.png)

**Comment by carlssonemil** [comment]
How did you try to share it?

Sharing just the link (https://damascus.now.sh/) should work.

**Comment by myounus96** [comment]
By clicking on facebook icon.
![image](https://user-images.githubusercontent.com/13608139/90330407-eb73af00-dfc5-11ea-9af6-e140443408ac.png)

**Comment by carlssonemil** [comment]
Oh, my bad, I confused this repository for another one. I'll look into it straight away! 😄

**Comment by myounus96** [comment]
> Oh, my bad, I confused this repository for another one. I'll look into it straight away!

Oh, and BTW it is working fine for twitter.

**Comment by carlssonemil** [comment]
I tried it just now on my end and it seems to be working fine.

Can you go to _chrome://extensions/_ in the search bar, find _Quotes New Tab_ and tell me the version number next to the extension name?

![Extension Version](https://i.gyazo.com/67fd27869b88b9d913d29a2895ebe844.png)

**Comment by myounus96** [comment]
Here you go, BTW my OS is ubuntu.
![image](https://user-images.githubusercontent.com/13608139/90330614-90db5280-dfc7-11ea-8ef4-71dec2d30ae8.png)

**Comment by myounus96** [comment]
Here is the chrome version.
![image](https://user-images.githubusercontent.com/13608139/90330710-60e07f00-dfc8-11ea-9065-caf3548ab23d.png)

**Comment by carlssonemil** [comment]
I had to update some information on Facebook's developer site. It should be working now! 👍

**Comment by myounus96** [comment]
> I had to update some information on Facebook's developer site. It should be working now!

Yup working fine now, Thanks a lot.
